; Auto-generated by EclipseNSIS InstallOptions Script Wizard
; 05.03.2009 12:32:28
[Settings]
NumFields=3

[Field 1]
Type=CheckBox
Left=40
Top=20
Right=160
Bottom=29
Text=CheckBox

[Field 2]
Type=Listbox
Left=40
Top=60
Right=170
Bottom=130

[Field 3]
Type=FileRequest
Left=40
Top=40
Right=240
Bottom=49
Filter=My Filter|*.*
