
: ONLINE? ( -- ? )  S" " SONLINE? ;

: ONLINE: eval-string, POSTPONE SONLINE? ; IMMEDIATE

\ : EXIST? ( a u --?)
\    DROP FIND-FIRST-FILE FIND-CLOSE
\    DUP IF NIP THEN ;

: EXIST: eval-string, POSTPONE EXIST? ; IMMEDIATE

: WIN-EXIST: eval-string, POSTPONE WIN-EXIST? ; IMMEDIATE

: PROC-EXIST: eval-string, POSTPONE PROC-EXIST? POSTPONE 0<> ; IMMEDIATE
: KILL: eval-string, POSTPONE KILL ; IMMEDIATE

: LOG: eval-string, eval-string, POSTPONE 2SWAP POSTPONE LOG2 ;  IMMEDIATE


: RASEntry:     eval-string, POSTPONE RASEntry ; IMMEDIATE
: RASPhone:     eval-string, POSTPONE RASPhone ; IMMEDIATE
: RASUser:      eval-string, POSTPONE RASUser ; IMMEDIATE
: RASPassword:  eval-string, POSTPONE RASPassword ; IMMEDIATE
: RASSecPassword:
            eval-string,
            POSTPONE DecP
            POSTPONE RASPassword ; IMMEDIATE 

: ?RAS-ERR ( --)
    RASError
    IF  
        256 PAD
        RASError
        RasGetErrorStringA 0=
        IF PAD ASCIIZ>
        ELSE S" RAS ERROR # %RASError N>S%" THEN
    ELSE
        S" RAS: no errors." 
    THEN
    CRON-LOG
;

: (DIAL:) ( a u attempts pause  -- )
    >R >R
    RASEntry
    R> R> 1 MAX 1000 * SWAP 1 MAX 
    0 DO (?DIAL) IF LEAVE ELSE ?RAS-ERR DUP PAUSE THEN LOOP
    DROP
;

: (#DIAL) #DIAL ?RAS-ERR ;
: (SHANGUP) SHANGUP ?RAS-ERR ;
: RASDomain:    eval-string, POSTPONE RASDomain ; IMMEDIATE
: DIAL: eval-string,
        number, number,
        POSTPONE (DIAL:) ; IMMEDIATE

: #DIAL:        eval-string, POSTPONE (#DIAL) ; IMMEDIATE
: HANGUP:       eval-string, POSTPONE (SHANGUP) ; IMMEDIATE
: HANGUP S" " (SHANGUP) ;


VARIABLE USER-TOKEN

: LOGON ( S" User" S" Password" --)
    DROP NIP SWAP >R >R
    USER-TOKEN LOGON32_PROVIDER_DEFAULT LOGON32_LOGON_INTERACTIVE
    R> 0 R> LogonUserA 0= IF S" LOGON error" CRON-LOG THEN 
;
    
: LOGON: eval-string, eval-string, POSTPONE LOGON ; IMMEDIATE

: MSG: eval-string, POSTPONE MsgBox ; IMMEDIATE
: ERR-MSG: eval-string, POSTPONE ErrMsgBox ; IMMEDIATE
: TMSG: eval-string, number, POSTPONE TimeMsgBox ; IMMEDIATE

: #Ping: eval-string, POSTPONE ROT POSTPONE PING ; IMMEDIATE
: Ping: 3 [COMPILE] LITERAL [COMPILE] #Ping: ; IMMEDIATE
: NHOST-EXIST: eval-string, number, POSTPONE PING ; IMMEDIATE
: HOST-EXIST: [COMPILE] Ping: ; IMMEDIATE

: FILE-EXIST: [COMPILE] EXIST: ; IMMEDIATE

: WIN-CLICK: eval-string, eval-string, POSTPONE WIN-CLICK ; IMMEDIATE
: WIN-CLOSE: eval-string, POSTPONE WIN-CLOSE ; IMMEDIATE

: WIN-HIDE: eval-string, POSTPONE WIN-HIDE ; IMMEDIATE
: WIN-SHOW: eval-string, POSTPONE WIN-SHOW ; IMMEDIATE
: WIN-MINIMIZE: eval-string, POSTPONE WIN-MINIMIZE ; IMMEDIATE
: WIN-MAXIMIZE: eval-string, POSTPONE WIN-MAXIMIZE ; IMMEDIATE
: WIN-RESTORE: eval-string, POSTPONE WIN-RESTORE ; IMMEDIATE
: (WIN-TOPMOST) WIN-EXIST? IF WIN-HWND WIN-TOPMOST THEN ;
: WIN-TOPMOST:  eval-string, POSTPONE (WIN-TOPMOST) ; IMMEDIATE

: WIN-SET-TITLE: eval-string, eval-string, POSTPONE WIN-SET-TITLE ; IMMEDIATE

: (WIN-NOTOPMOST) WIN-EXIST? IF WIN-HWND WIN-NOTOPMOST THEN ;
: WIN-NOTOPMOST:  eval-string, POSTPONE (WIN-NOTOPMOST) ; IMMEDIATE

: WIN-TERMINATE: eval-string, POSTPONE WIN-TERMINATE ; IMMEDIATE
: WIN-DESTROY: eval-string, POSTPONE WIN-DESTROY ; IMMEDIATE
: WIN-ACTIVE: eval-string, POSTPONE WIN-ACTIVE? ; IMMEDIATE
: WIN-ACTIVATE: eval-string,  POSTPONE WIN-ACTIVATE ; IMMEDIATE
: SEND-KEYS: eval-string, POSTPONE SEND-KEYS ; IMMEDIATE

: xy, number, number, ;

: SEND-KEYS-DELAY: xy, POSTPONE SEND-KEYS-DELAY ; IMMEDIATE

: WIN-MOVE:  xy, POSTPONE WIN-MOVE ; IMMEDIATE
: WIN-MOVER: xy, POSTPONE WIN-MOVER ; IMMEDIATE
: WIN-WAIT: number, POSTPONE WIN-WAIT ; IMMEDIATE

: MOUSE-MOVE: xy, POSTPONE MOUSE-MOVE ; IMMEDIATE
: MOUSE-MOVER: xy, POSTPONE MOUSE-MOVER ; IMMEDIATE
: MOUSE-MOVEW: xy, POSTPONE MOUSE-MOVEW ; IMMEDIATE

: WIN-SEND-KEYS ( a-win u-win a-keys u-keys -- )
    2SWAP 2DUP WIN-EXIST?
    IF
        WIN-ACTIVATE 
        1000 PAUSE
        SEND-KEYS
    ELSE
        2DROP 2DROP
    THEN
;

: WIN-SEND-KEYS:
    eval-string, eval-string,
    POSTPONE WIN-SEND-KEYS
; IMMEDIATE

: crlf LT LTL @ ;

VARIABLE without-plugins
: INCLUDE get-string without-plugins @ 0= 
    IF CUR-OR-HOME-OR-NNCRON-FILE? IF INCLUDED ELSE 2DROP THEN 
    ELSE 2DROP THEN ;

: FILE-SIZE: eval-string, POSTPONE FSIZE ; IMMEDIATE

: FILE-EMPTY ( addr u -- ud )  FSIZE OR 0= ;
: FILE-EMPTY: eval-string, POSTPONE FILE-EMPTY ; IMMEDIATE
: FILE-DATE: eval-string, POSTPONE FCDATE ; IMMEDIATE
: FILE-CREATION-DATE: eval-string, POSTPONE FCDATE ; IMMEDIATE
: FILE-ACCESS-DATE: eval-string, POSTPONE FADATE ; IMMEDIATE
: FILE-WRITE-DATE: eval-string, POSTPONE FWDATE ; IMMEDIATE

: FOR-FILES: eval-string,  POSTPONE FOR-FILES ; IMMEDIATE
: FOR-PROCS: eval-string,  POSTPONE FOR-PROCS ; IMMEDIATE
: STR: ?COMP eval-string, ; IMMEDIATE
: START-IN: eval-string, POSTPONE START-IN ; IMMEDIATE

: PLAY-SOUND: 
    SND_ASYNC POSTPONE LITERAL
    eval-string, 
    POSTPONE PLAY-SOUND
; IMMEDIATE    

: PLAY-SOUNDW: 
    SND_SYNC POSTPONE LITERAL
    eval-string, 
    POSTPONE PLAY-SOUND
; IMMEDIATE    


: QUERY: eval-string, POSTPONE QUERY  ; IMMEDIATE
: TQUERY: eval-string, number, 
    CHAR DUP [CHAR] y = SWAP [CHAR] Y = OR POSTPONE LITERAL
    POSTPONE TQUERY  ; IMMEDIATE

: FILE-WRITE: eval-string, eval-string,
    POSTPONE 2SWAP POSTPONE FWRITE ; IMMEDIATE

: FILE-APPEND: eval-string, eval-string,
    POSTPONE 2SWAP POSTPONE FAPPEND ; IMMEDIATE

\ : FILE-READ: eval-string, eval-string,
\    POSTPONE 2SWAP POSTPONE FWRITE ; IMMEDIATE

: FILE-RENAME: eval-string, eval-string,  POSTPONE FRENAME ; IMMEDIATE
: FILE-COPY: eval-string, eval-string, POSTPONE FCOPY ; IMMEDIATE
: FILE-MOVE: eval-string, eval-string, POSTPONE FMOVE ; IMMEDIATE
: FILE-DELETE: eval-string, POSTPONE FDELETE ; IMMEDIATE
: FILE-CREATE: eval-string, POSTPONE FCREATE ; IMMEDIATE
: FILE-CROP: eval-string, number, number, POSTPONE FCROPkb ; IMMEDIATE

: DIR-DELETE: eval-string, POSTPONE DIR-DELETE ; IMMEDIATE
: DIR-CREATE: eval-string, POSTPONE DIR-CREATE ; IMMEDIATE
: DIR-EMPTY: eval-string, POSTPONE DIR-EMPTY? ; IMMEDIATE
: DIR-SIZE: eval-string, POSTPONE DIR-SIZE ; IMMEDIATE

: BEEP: number, number, ( POSTPONE SWAP) POSTPONE BEEP ; IMMEDIATE
: PAUSE: get-string S>MS POSTPONE LITERAL POSTPONE PAUSE ; IMMEDIATE
    
: NOT 0= ;

: PURGE-OLD:  eval-string, number, POSTPONE PURGE-OLD ; IMMEDIATE
: PURGE-OLDW: eval-string, number, POSTPONE PURGE-OLDW ; IMMEDIATE
: PURGE-OLDA: eval-string, number, POSTPONE PURGE-OLDA ; IMMEDIATE

: POP3-CHECK: eval-string, eval-string, eval-string, 
    POSTPONE POP3-CHECK ; IMMEDIATE

: RE-ALL: eval-string, eval-string, POSTPONE RE-ALL ; IMMEDIATE
: RE-MATCH: eval-string, eval-string, POSTPONE RE-MATCH ; IMMEDIATE

: FREE-SPACE:
    BL WORD 1+ C@ POSTPONE LITERAL
    POSTPONE FREE-SPACE
; IMMEDIATE

: BackupPath: get-string S>ZALLOC BACKUP-PATH ! ;

: WatchWinCreateDelay: get-number WatchWinCreateDelay ! ;

: REG-SZ: eval-string, eval-string, POSTPONE REG-SZ ; IMMEDIATE 
: REG-DWORD: eval-string, number, POSTPONE REG-DWORD ; IMMEDIATE 
: REG-DELETE-KEY: eval-string, POSTPONE REG-DELETE-KEY ; IMMEDIATE 
: REG-DELETE-VALUE: eval-string, POSTPONE REG-DELETE-VALUE ; IMMEDIATE 
: GET-REG: eval-string, POSTPONE GET-REG ; IMMEDIATE 


: FOR-WINDOWS: eval-string, POSTPONE FOR-WINDOWS ; IMMEDIATE 
: FOR-CHILD-WINDOWS: eval-string, POSTPONE FOR-CHILD-WINDOWS ; IMMEDIATE 

: SYS-SET
    BL SKIP 
    [CHAR] = 
    PARSE -TRAILING \ 2DUP TYPE CR
    [CHAR] " DUP PeekChar <>
    IF DROP 1 THEN
    DUP SKIP
    PARSE \ 2DUP TYPE CR
    EVAL-SUBST
    (SYS-SET)
;

: CD-TRAY-EJECT: get-string DROP C@ POSTPONE LITERAL POSTPONE CD-TRAY-EJECT POSTPONE DROP ; IMMEDIATE
: CD-TRAY-CLOSE: get-string DROP C@ POSTPONE LITERAL POSTPONE CD-TRAY-CLOSE POSTPONE DROP ; IMMEDIATE
: IS-CD-PRESENT: get-string DROP C@ POSTPONE LITERAL POSTPONE IS-CD-PRESENT ; IMMEDIATE
